# Generated by Django 4.0.1 on 2022-01-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegAndAuth', '0002_remove_message_user_message_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
