# Generated by Django 4.0.1 on 2022-01-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegAndAuth', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Username',
            new_name='Username_Id',
        ),
    ]
