# Generated by Django 4.0.1 on 2022-01-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegAndAuth', '0006_encrypting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypting',
            name='Key',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
